service: aws-connect-vanify
app: aws-connect-vanify
org: bradenm

frameworkVersion: '2'

plugins:
    - serverless-plugin-scripts

provider:
  name: aws
  lambdaHashingVersion: 20201221
  iamRoleStatements: ${file(resources/roles.yml):RoleStatements}
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  ecr:
    images:
      aws-connect-vanify:
        path: ./

  stage: dev
  region: us-east-1

custom:
  scripts:
    commands:
      update-flow: python -m deploy deploy-flow aws-connect-vanify ${sls:stage}
    hooks:
      'deploy:finalize': python -m deploy deploy-flow aws-connect-vanify ${sls:stage}

functions:
  vanify:
    description: AWS Connect Vanify Entrypoint
    timeout: 15
    memorySize: 256
    image:
      name: aws-connect-vanify
  recent:
    description: Api endpoint for retrieving recent callers.
    memorySize: 128
    image:
      name: aws-connect-vanify
      command:
        - vanify.app.recent
    events:
      - http:
          path: recent
          method: get
          cors: true

resources:
  - ${file(resources/dynamodb.yml)}
